# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QPropertyAnimation, QEasingCurve, QTimer, QThread, pyqtSignal, Qt, QRect
from PyQt5.QtGui import QPainter, QColor, QPen, QFont
from PyQt5.QtWidgets import QWidget
import joblib
import numpy as np
import pandas as pd
import time
import random
from datetime import datetime
import re

# Custom Circular Progress Bar Widget
class CircularProgressBar(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.value = 0
        self.maximum = 100
        self.setMinimumSize(200, 200)
        
    def setValue(self, value):
        self.value = value
        self.update()
    
    def paintEvent(self, event):
        painter = QPainter(self)
        painter.setRenderHint(QPainter.Antialiasing)
        
        # Calculate dimensions
        width = self.width()
        height = self.height()
        side = min(width, height)
        
        # Center the circle
        painter.translate(width / 2, height / 2)
        
        # Draw background circle
        pen = QPen()
        pen.setWidth(15)
        pen.setColor(QColor(49, 65, 88))
        pen.setCapStyle(Qt.RoundCap)
        painter.setPen(pen)
        painter.drawArc(int(-side/2 + 15), int(-side/2 + 15), int(side - 30), int(side - 30), 0, 360 * 16)
        
        # Draw progress arc
        pen.setColor(QColor(82, 161, 252))
        pen.setWidth(15)
        painter.setPen(pen)
        angle = int(360 * 16 * self.value / self.maximum)
        painter.drawArc(int(-side/2 + 15), int(-side/2 + 15), int(side - 30), int(side - 30), 90 * 16, -angle)
        
        # Draw percentage text
        painter.setPen(QColor(255, 255, 255))
        font = QFont()
        font.setPointSize(24)
        font.setBold(True)
        painter.setFont(font)
        painter.drawText(QRect(int(-side/2), int(-side/2), int(side), int(side)), Qt.AlignCenter, f"{self.value}%")

# Base directory
base_dir = os.path.dirname(os.path.abspath(__file__))

# Load Models
mem_svm_model = joblib.load(os.path.join(base_dir, "Models", "Memory Model - SVM.pkl"))
net_dt_model = joblib.load(os.path.join(base_dir, "Models", "Network Model - Decision Tree.pkl"))

# Load Network Flow Data
network_flow_path = os.path.join(base_dir, "Network Flow", "Network_Validation_Set.csv")
try:
    network_flow_df_raw = pd.read_csv(network_flow_path)
    # Exclude the last column (label column)
    network_flow_df_raw = network_flow_df_raw.iloc[:, :-1]
    # Store source IPs and ports before dropping them
    network_flow_src_ips = network_flow_df_raw['Src IP'].copy() if 'Src IP' in network_flow_df_raw.columns else None
    network_flow_src_ports = network_flow_df_raw['Src Port'].copy() if 'Src Port' in network_flow_df_raw.columns else None
    
    # Exclude columns that the network model doesn't need
    columns_to_drop = [
        'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'URG Flag Count', 
        'CWR Flag Count', 'ECE Flag Count', 'Fwd Bytes/Bulk Avg', 'Fwd Bulk Rate Avg',
        'Flow ID', 'Src IP', 'Dst IP', 'Timestamp', 'Src Port', 'Dst Port', 'Malware_Sample'
    ]
    # Drop columns that exist in the dataframe
    columns_to_drop = [col for col in columns_to_drop if col in network_flow_df_raw.columns]
    network_flow_df = network_flow_df_raw.drop(columns=columns_to_drop)
    print(f"Loaded network flow data: {len(network_flow_df)} rows, {len(network_flow_df.columns)} columns")
except Exception as e:
    print(f"Warning: Could not load network flow data from {network_flow_path}: {e}")
    print("Falling back to hardcoded samples")
    network_flow_df = None
    network_flow_src_ips = None
    network_flow_src_ports = None

# Load Memory Dump Data
memory_dump_path = os.path.join(base_dir, "Memory Dump", "Memory_Validation_Set.csv")
try:
    memory_dump_df = pd.read_csv(memory_dump_path)
    # Exclude the last column (label column)
    memory_dump_df = memory_dump_df.iloc[:, :-1]
    print(f"Loaded memory dump data: {len(memory_dump_df)} rows, {len(memory_dump_df.columns)} columns")
except Exception as e:
    print(f"Warning: Could not load memory dump data from {memory_dump_path}: {e}")
    print("Falling back to hardcoded samples")
    memory_dump_df = None

# Worker thread for network scanning
class NetworkScanWorker(QThread):
    scan_complete = pyqtSignal(object, int, str, int)
    current_row_index = 0
    
    def run(self):
        """Run the network scan in a separate thread"""
        time.sleep(1)
        
        # Use current row index and increment for next scan
        current_index = NetworkScanWorker.current_row_index
        sample_row = network_flow_df.iloc[current_index:current_index+1]
        
        # Get source IP and port if available
        src_ip = network_flow_src_ips.iloc[current_index] if network_flow_src_ips is not None else "N/A"
        src_port = int(network_flow_src_ports.iloc[current_index]) if network_flow_src_ports is not None else 0
        
        # Convert to numpy array for prediction
        sample = sample_row.values
        row_number = current_index + 1  # 1-based indexing for display
        
        # Increment for next scan, wrap around if at the end
        NetworkScanWorker.current_row_index = (current_index + 1) % len(network_flow_df)
        
        netdtPredict = net_dt_model.predict(sample)
        self.scan_complete.emit(netdtPredict, row_number, src_ip, src_port)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        base_dir = os.path.dirname(os.path.abspath(__file__))
        assets_dir = os.path.join(base_dir, "Assets")
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 980)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(22, 36, 85);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Create scroll area
        self.scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_area.setGeometry(QtCore.QRect(0, 0, 1440, 980))
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setStyleSheet("QScrollArea { border: none; background-color: transparent; }")
        self.scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        
        # Create container widget for scroll area content
        self.scroll_content = QtWidgets.QWidget()
        self.scroll_content.setMinimumSize(1440, 980)
        self.scroll_area.setWidget(self.scroll_content)
        
        self.top_bar = QtWidgets.QFrame(self.scroll_content)
        self.top_bar.setGeometry(QtCore.QRect(-1, -1, 1441, 111))
        self.top_bar.setStyleSheet("background-color: rgb(10, 19, 52);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        
        self.exit_icon = QtWidgets.QLabel(self.top_bar)
        self.exit_icon.setGeometry(QtCore.QRect(1390, 12, 34, 34))
        self.exit_icon.setStyleSheet("border: none;\n"
                                        "border-radius: none;")
        self.exit_icon.setText("")
        self.exit_icon.setPixmap(QtGui.QPixmap(os.path.join(assets_dir, "phase2_icon.svg")))
        self.exit_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.exit_icon.setObjectName("exit_icon")
        self.exit_icon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_icon.mousePressEvent = lambda event: QtWidgets.QApplication.quit()
        
        # Labels
        self.two_phase_text_label = QtWidgets.QLabel(self.scroll_content)
        self.two_phase_text_label.setGeometry(QtCore.QRect(406, 160, 629, 58))
        font = QtGui.QFont()
        font.setPointSize(49)
        font.setBold(True)
        font.setWeight(75)
        self.two_phase_text_label.setFont(font)
        self.two_phase_text_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.two_phase_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.two_phase_text_label.setWordWrap(True)
        self.two_phase_text_label.setObjectName("two_phase_text_label")
        
        self.malware_detection_text_label = QtWidgets.QLabel(self.scroll_content)
        self.malware_detection_text_label.setGeometry(QtCore.QRect(406, 220, 629, 58))
        font = QtGui.QFont()
        font.setPointSize(49)
        font.setBold(True)
        font.setWeight(75)
        self.malware_detection_text_label.setFont(font)
        self.malware_detection_text_label.setStyleSheet("color: rgb(82, 161, 252);")
        self.malware_detection_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.malware_detection_text_label.setWordWrap(True)
        self.malware_detection_text_label.setObjectName("malware_detection_text_label")
        
        self.description_text_label = QtWidgets.QLabel(self.scroll_content)
        self.description_text_label.setGeometry(QtCore.QRect(309, 293, 823, 83))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.description_text_label.setFont(font)
        self.description_text_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.description_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.description_text_label.setWordWrap(True)
        self.description_text_label.setObjectName("description_text_label")
        
        self.new_scan_button = QtWidgets.QPushButton(self.scroll_content)
        self.new_scan_button.setGeometry(QtCore.QRect(1109, 370, 167, 42))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        self.new_scan_button.setFont(font)
        self.new_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                "background-color: #324259;\n"
                                                "border: 1px solid #728EB8;\n"
                                                "border-radius: 8px;")
        self.new_scan_button.setObjectName("new_scan_button")
        self.new_scan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_scan_button.hide()
        
        # Phase 1 Frame
        self.phase1_frame = QtWidgets.QFrame(self.scroll_content)
        self.phase1_frame.setGeometry(QtCore.QRect(164, 424, 531, 80))
        self.phase1_frame.setStyleSheet("background-color: rgb(13, 22, 51);\n"
        "border: 1px solid #728EB8;\n"
        "border-radius: 15px;")
        self.phase1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phase1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phase1_frame.setObjectName("phase1_frame")
        
        self.phase1_icon_frame = QtWidgets.QFrame(self.phase1_frame)
        self.phase1_icon_frame.setGeometry(QtCore.QRect(20, 14, 51, 51))
        self.phase1_icon_frame.setStyleSheet("background-color: rgb(49, 65, 88);\n"
        "border: 1px solid #728EB8;\n"
        "border-radius: 15px;")
        self.phase1_icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phase1_icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phase1_icon_frame.setObjectName("phase1_icon_frame")
        
        self.phase1_icon = QtWidgets.QLabel(self.phase1_icon_frame)
        self.phase1_icon.setGeometry(QtCore.QRect(9, 9, 34, 34))
        self.phase1_icon.setStyleSheet("border: none;\n"
        "border-radius: none;")
        self.phase1_icon.setText("")
        self.phase1_icon.setPixmap(QtGui.QPixmap(os.path.join(assets_dir, "phase1_icon.svg")))
        self.phase1_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.phase1_icon.setObjectName("phase1_icon")
        
        self.phase1_text_label = QtWidgets.QLabel(self.phase1_frame)
        self.phase1_text_label.setGeometry(QtCore.QRect(80, 20, 63, 11))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.phase1_text_label.setFont(font)
        self.phase1_text_label.setStyleSheet("color: rgb(176, 185, 197);\n"
        "border: none;")
        self.phase1_text_label.setObjectName("phase1_text_label")
        
        self.network_scanning_text_label = QtWidgets.QLabel(self.phase1_frame)
        self.network_scanning_text_label.setGeometry(QtCore.QRect(80, 37, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.network_scanning_text_label.setFont(font)
        self.network_scanning_text_label.setStyleSheet("color: rgb(176, 185, 197);\n"
        "color: rgb(255, 255, 255);\n"
        "border: none;")
        self.network_scanning_text_label.setObjectName("network_scanning_text_label")
        
        # Notes label above start_scan_frame
        self.notes_label = QtWidgets.QLabel(self.scroll_content)
        self.notes_label.setGeometry(QtCore.QRect(164, 514, 600, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.notes_label.setFont(font)
        self.notes_label.setStyleSheet("background-color: none;")
        self.notes_label.setText("<span style='color: rgb(0, 255, 0); font-weight: bold;'>Benign = Safe</span>       <span style='color: rgb(255, 0, 0); font-weight: bold;'>Malicious = SUSPECTED THREAT</span>")
        self.notes_label.setObjectName("notes_label")
        self.notes_label.hide()
        
        # Start Scan Frame
        self.start_scan_frame = QtWidgets.QFrame(self.scroll_content)
        self.start_scan_frame.setGeometry(QtCore.QRect(164, 544, 1112, 419))
        self.start_scan_frame.setStyleSheet("background-color: rgba(13, 22, 51, 0.4);\n"
        "border-radius: 15px;")
        self.start_scan_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_scan_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_scan_frame.setObjectName("start_scan_frame")
        
        self.scan_icon = QtWidgets.QLabel(self.start_scan_frame)
        self.scan_icon.setGeometry(QtCore.QRect(516, 56, 81, 90))
        self.scan_icon.setStyleSheet("background-color: none;")
        self.scan_icon.setText("")
        self.scan_icon.setPixmap(QtGui.QPixmap(os.path.join(assets_dir, "scan_icon.svg")))
        self.scan_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.scan_icon.setObjectName("scan_icon")
        
        self.ready_to_scan_text_label = QtWidgets.QLabel(self.start_scan_frame)
        self.ready_to_scan_text_label.setGeometry(QtCore.QRect(434, 170, 245, 26))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.ready_to_scan_text_label.setFont(font)
        self.ready_to_scan_text_label.setStyleSheet("color: rgb(255, 255, 255);\n"
        "background-color: none;")
        self.ready_to_scan_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ready_to_scan_text_label.setObjectName("ready_to_scan_text_label")
        
        self.start_scan_desription = QtWidgets.QLabel(self.start_scan_frame)
        self.start_scan_desription.setGeometry(QtCore.QRect(229, 218, 655, 15))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_scan_desription.setFont(font)
        self.start_scan_desription.setStyleSheet("background-color: none;\n"
        "color: rgb(176, 185, 197);")
        self.start_scan_desription.setAlignment(QtCore.Qt.AlignCenter)
        self.start_scan_desription.setObjectName("start_scan_desription")
        
        self.start_scan_button = QtWidgets.QPushButton(self.start_scan_frame)
        self.start_scan_button.setGeometry(QtCore.QRect(444, 269, 225, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.start_scan_button.setFont(font)
        self.start_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                "background-color: rgb(47, 139, 255);\n"
                                                "border: 1px solid #728EB8;\n"
                                                "border-radius: 15px;")
        self.start_scan_button.setObjectName("start_scan_button")
        self.start_scan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        
        self.pause_scan_button = QtWidgets.QPushButton(self.start_scan_frame)
        self.pause_scan_button.setGeometry(QtCore.QRect(925, 20, 167, 42))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setWeight(75)
        self.pause_scan_button.setFont(font)
        self.pause_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color: #FF9020;\n"
                                              "border: 1px solid #728EB8;\n"
                                              "border-radius: 8px;")
        self.pause_scan_button.setObjectName("pause_scan_button")
        self.pause_scan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pause_scan_button.hide()
        
        # Auto Resume Checkbox
        self.auto_resume_checkbox = QtWidgets.QCheckBox(self.start_scan_frame)
        self.auto_resume_checkbox.setGeometry(QtCore.QRect(800, 25, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.auto_resume_checkbox.setFont(font)
        self.auto_resume_checkbox.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                 "background-color: none;\n"
                                                 "border: none;")
        self.auto_resume_checkbox.setText("Auto Resume")
        self.auto_resume_checkbox.setObjectName("auto_resume_checkbox")
        self.auto_resume_checkbox.hide()
        
        self.network_scanning_list_frame = QtWidgets.QFrame(self.start_scan_frame)
        self.network_scanning_list_frame.setGeometry(QtCore.QRect(20, 90, 1071, 200))
        self.network_scanning_list_frame.setStyleSheet("background-color: rgb(13, 22, 51);\n"
        "border-radius: 15px;")
        self.network_scanning_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.network_scanning_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.network_scanning_list_frame.setObjectName("network_scanning_list_frame")
        self.network_scanning_list_frame.hide()
        
        # Add text display for network scan results
        self.network_scan_results_text = QtWidgets.QTextEdit(self.network_scanning_list_frame)
        self.network_scan_results_text.setGeometry(QtCore.QRect(15, 15, 1041, 170))
        self.network_scan_results_text.setStyleSheet("border: none;\n"
                                                       "border-radius: 10px;\n"
                                                       "color: rgb(255, 255, 255);\n"
                                                       "font-size: 12pt;")
        self.network_scan_results_text.setReadOnly(True)
        self.network_scan_results_text.setObjectName("network_scan_results_text")
        
        self.network_scanning_list_frame_2 = QtWidgets.QFrame(self.start_scan_frame)
        self.network_scanning_list_frame_2.setGeometry(QtCore.QRect(20, 311, 1071, 200))
        self.network_scanning_list_frame_2.setStyleSheet("background-color: rgba(255, 144, 32, 0.4);\n"
                                                            "border-radius: 15px;\n"
                                                            "border: 1px solid rgb(255, 144, 32);")
        self.network_scanning_list_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.network_scanning_list_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.network_scanning_list_frame_2.setObjectName("network_scanning_list_frame_2")
        self.network_scanning_list_frame_2.hide()
        
        # Add label for network threats
        self.network_threats_label = QtWidgets.QLabel(self.network_scanning_list_frame_2)
        self.network_threats_label.setGeometry(QtCore.QRect(15, 10, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.network_threats_label.setFont(font)
        self.network_threats_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                   "background-color: none;\n"
                                                   "border: none;")
        self.network_threats_label.setText("Network Threats Detected")
        self.network_threats_label.setObjectName("network_threats_label")
        
        # Add text display for malicious scan results
        self.malicious_scan_results_text = QtWidgets.QTextEdit(self.network_scanning_list_frame_2)
        self.malicious_scan_results_text.setGeometry(QtCore.QRect(15, 45, 1041, 140))
        self.malicious_scan_results_text.setStyleSheet("background-color: rgba(255, 144, 32, 0);\n"
                                                        "border: none;\n"
                                                        "border-radius: 10px;\n"
                                                        "color: rgb(255, 255, 255);\n"
                                                        "font-size: 12pt;")
        self.malicious_scan_results_text.setReadOnly(True)
        self.malicious_scan_results_text.setObjectName("malicious_scan_results_text")
        
        self.network_active_scanning_icon = QtWidgets.QLabel(self.start_scan_frame)
        self.network_active_scanning_icon.setGeometry(QtCore.QRect(20, 20, 34, 34))
        self.network_active_scanning_icon.setStyleSheet("border: none;\n"
                                                        "border-radius: none;")
        self.network_active_scanning_icon.setText("")
        self.network_active_scanning_icon.setPixmap(QtGui.QPixmap(os.path.join(assets_dir, "phase1_icon.svg")))
        self.network_active_scanning_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.network_active_scanning_icon.setObjectName("network_active_scanning_icon")
        self.network_active_scanning_icon.hide()
        
        self.network_active_scanning_text_label = QtWidgets.QLabel(self.start_scan_frame)
        self.network_active_scanning_text_label.setGeometry(QtCore.QRect(60, 20, 245, 33))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.network_active_scanning_text_label.setFont(font)
        self.network_active_scanning_text_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                                "background-color: none;\n"
                                                                "border: none;")
        self.network_active_scanning_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.network_active_scanning_text_label.setObjectName("network_active_scanning_text_label")
        self.network_active_scanning_text_label.hide()
        
        # Start Scan Frame Memory
        self.start_scan_memory_frame = QtWidgets.QFrame(self.scroll_content)
        self.start_scan_memory_frame.setGeometry(QtCore.QRect(164, 900, 1112, 550))
        self.start_scan_memory_frame.setStyleSheet("background-color: rgb(13, 22, 51);\n"
                                                        "border-radius: 15px;\n"
                                                        "border: 1px solid #728EB8;")
        self.start_scan_memory_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_scan_memory_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_scan_memory_frame.setObjectName("start_scan_memory_frame")
        self.start_scan_memory_frame.hide()
        
        self.memory_active_scanning_icon = QtWidgets.QLabel(self.start_scan_memory_frame)
        self.memory_active_scanning_icon.setGeometry(QtCore.QRect(20, 20, 34, 34))
        self.memory_active_scanning_icon.setStyleSheet("border: none;\n"
                                                        "border-radius: none;")
        self.memory_active_scanning_icon.setText("")
        self.memory_active_scanning_icon.setPixmap(QtGui.QPixmap(os.path.join(assets_dir, "phase2_icon.svg")))
        self.memory_active_scanning_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.memory_active_scanning_icon.setObjectName("memory_active_scanning_icon")
        self.memory_active_scanning_icon.hide()
        
        self.memory_active_scanning_text_label = QtWidgets.QLabel(self.start_scan_memory_frame)
        self.memory_active_scanning_text_label.setGeometry(QtCore.QRect(60, 20, 245, 33))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.memory_active_scanning_text_label.setFont(font)
        self.memory_active_scanning_text_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                        "background-color: none;\n"
                                                        "border: none;")
        self.memory_active_scanning_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.memory_active_scanning_text_label.setObjectName("memory_active_scanning_text_label")
        self.memory_active_scanning_text_label.hide()
        
        # Memory scan trigger source label
        self.memory_trigger_source_label = QtWidgets.QLabel(self.start_scan_memory_frame)
        self.memory_trigger_source_label.setGeometry(QtCore.QRect(356, 20, 400, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.memory_trigger_source_label.setFont(font)
        self.memory_trigger_source_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                        "background-color: rgba(0, 100, 0, 0.3);\n"
                                                        "border: 2px solid rgb(0, 200, 0);\n"
                                                        "border-radius: 8px;\n"
                                                        "padding: 5px;")
        self.memory_trigger_source_label.setAlignment(QtCore.Qt.AlignCenter)
        self.memory_trigger_source_label.setObjectName("memory_trigger_source_label")
        self.memory_trigger_source_label.hide()
        
        # Memory scan result label
        self.memory_result_label = QtWidgets.QLabel(self.start_scan_memory_frame)
        self.memory_result_label.setGeometry(QtCore.QRect(256, 65, 600, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.memory_result_label.setFont(font)
        self.memory_result_label.setStyleSheet("color: rgb(255, 255, 255);"
                                                "background-color: none;"
                                                "border: none;")
        self.memory_result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.memory_result_label.setObjectName("memory_result_label")
        self.memory_result_label.hide()
        
        # Circular progress bar for memory scanning
        self.memory_progress_bar = CircularProgressBar(self.start_scan_memory_frame)
        self.memory_progress_bar.setGeometry(QtCore.QRect(456, 110, 200, 200))
        self.memory_progress_bar.setObjectName("memory_progress_bar")
        
        # Force Memory Scan button
        self.force_memory_scan_button = QtWidgets.QPushButton(self.start_scan_memory_frame)
        self.force_memory_scan_button.setGeometry(QtCore.QRect(925, 20, 167, 42))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.force_memory_scan_button.setFont(font)
        self.force_memory_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                     "background-color: rgb(255, 69, 0);\n"
                                                     "border: 1px solid #728EB8;\n"
                                                     "border-radius: 8px;")
        self.force_memory_scan_button.setText("Force Memory Scan")
        self.force_memory_scan_button.setObjectName("force_memory_scan_button")
        self.force_memory_scan_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.force_memory_scan_button.clicked.connect(self.handle_force_cancel_button)
        self.force_memory_scan_button.hide()
        
        # Recent Memory Scans label
        self.recent_memory_scans_label = QtWidgets.QLabel(self.start_scan_memory_frame)
        self.recent_memory_scans_label.setGeometry(QtCore.QRect(20, 320, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recent_memory_scans_label.setFont(font)
        self.recent_memory_scans_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                       "background-color: none;\n"
                                                       "border: none;")
        self.recent_memory_scans_label.setText("Recent Memory Scans")
        self.recent_memory_scans_label.setObjectName("recent_memory_scans_label")
        
        # Memory scan history text widget
        self.memory_scan_history_text = QtWidgets.QTextEdit(self.start_scan_memory_frame)
        self.memory_scan_history_text.setGeometry(QtCore.QRect(20, 355, 1071, 175))
        self.memory_scan_history_text.setStyleSheet("background-color: rgb(10, 19, 52);\n"
                                                      "border: none;\n"
                                                      "border-radius: 10px;\n"
                                                      "color: rgb(255, 255, 255);\n"
                                                      "font-size: 11pt;\n"
                                                      "padding: 10px;")
        self.memory_scan_history_text.setReadOnly(True)
        self.memory_scan_history_text.setObjectName("memory_scan_history_text")
        
        # Phase 2 Frame
        self.phase2_frame = QtWidgets.QFrame(self.scroll_content)
        self.phase2_frame.setGeometry(QtCore.QRect(745, 424, 531, 80))
        self.phase2_frame.setStyleSheet("background-color: rgb(13, 22, 51);\n"
        "border: 1px solid #728EB8;\n"
        "border-radius: 15px;")
        self.phase2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phase2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phase2_frame.setObjectName("phase2_frame")
        
        self.phase2_icon_frame = QtWidgets.QFrame(self.phase2_frame)
        self.phase2_icon_frame.setGeometry(QtCore.QRect(20, 14, 51, 51))
        self.phase2_icon_frame.setStyleSheet("background-color: rgb(49, 65, 88);\n"
        "border: 1px solid #728EB8;\n"
        "border-radius: 15px;")
        self.phase2_icon_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.phase2_icon_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.phase2_icon_frame.setObjectName("phase2_icon_frame")
        
        self.phase2_icon = QtWidgets.QLabel(self.phase2_icon_frame)
        self.phase2_icon.setGeometry(QtCore.QRect(9, 9, 34, 34))
        self.phase2_icon.setStyleSheet("border: none;\n"
        "border-radius: none;")
        self.phase2_icon.setText("")
        self.phase2_icon.setPixmap(QtGui.QPixmap(os.path.join(assets_dir, "phase2_icon.svg")))
        self.phase2_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.phase2_icon.setObjectName("phase2_icon")
        
        self.phase2_text_label = QtWidgets.QLabel(self.phase2_frame)
        self.phase2_text_label.setGeometry(QtCore.QRect(80, 20, 63, 11))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.phase2_text_label.setFont(font)
        self.phase2_text_label.setStyleSheet("color: rgb(176, 185, 197);\n"
        "border: none;")
        self.phase2_text_label.setObjectName("phase2_text_label")
        
        self.memory_scanning_text_label = QtWidgets.QLabel(self.phase2_frame)
        self.memory_scanning_text_label.setGeometry(QtCore.QRect(80, 37, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.memory_scanning_text_label.setFont(font)
        self.memory_scanning_text_label.setStyleSheet("color: rgb(176, 185, 197);\n"
        "color: rgb(255, 255, 255);\n"
        "border: none;")
        self.memory_scanning_text_label.setObjectName("memory_scanning_text_label")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Center the window on screen
        screen_geometry = QtWidgets.QApplication.desktop().screenGeometry()
        x = (screen_geometry.width() - MainWindow.width()) // 2
        y = (screen_geometry.height() - MainWindow.height()) // 2
        MainWindow.move(x, y)
        
        self.start_scan_button.clicked.connect(self.animate_scan_start)
        self.new_scan_button.clicked.connect(self.reset_to_initial_state)
        self.pause_scan_button.clicked.connect(self.toggle_pause_scan)
        
        # Setup timer for continuous network scanning
        self.network_scan_timer = QTimer()
        self.network_scan_timer.timeout.connect(self.run_network_scan)
        self.scan_count = 0
        self.current_row_index = 0
        self.is_paused = False
        
        # Setup timer for memory progress bar animation
        self.memory_progress_timer = QTimer()
        self.memory_progress_timer.timeout.connect(self.update_memory_progress)
        self.memory_progress_value = 0
        self.threat_detected = False
        self.trigger_ip = "N/A"
        self.trigger_port = 0
        
        # Initialize scan worker
        self.scan_worker = None
        
        # Auto resume flag
        self.auto_resume_enabled = False
        self.auto_resume_checkbox.stateChanged.connect(self.on_auto_resume_changed)
        
        # Load history from file
        self.history_file_path = os.path.join(os.path.dirname(__file__), "Memory Dump", "scan_history.txt")
        self.load_history_from_file()
    
    def save_history_entry(self, entry_html):
        """Save a history entry to file"""
        try:
            # Create Memory Dump folder if it doesn't exist
            memory_dump_dir = os.path.join(os.path.dirname(__file__), "Memory Dump")
            os.makedirs(memory_dump_dir, exist_ok=True)
            
            # Append entry to file
            with open(self.history_file_path, 'a', encoding='utf-8') as f:
                # Remove HTML tags for file storage, keep plain text format
                # Extract text from HTML
                plain_text = re.sub('<[^<]+?>', '', entry_html)
                f.write(plain_text.strip() + '\n')
        except Exception as e:
            print(f"Error saving history: {e}")
    
    def load_history_from_file(self):
        """Load history from file on startup"""
        try:
            if os.path.exists(self.history_file_path):
                with open(self.history_file_path, 'r', encoding='utf-8') as f:
                    lines = f.readlines()
                    for line in lines:
                        if line.strip():
                            # Parse the line and convert back to HTML format
                            if 'NO MALWARE DETECTED' in line:
                                parts = line.split('|')
                                result = 'NO MALWARE DETECTED'
                                color = 'rgb(0, 255, 0)'
                            elif 'MALWARE DETECTED' in line:
                                parts = line.split('|')
                                result = 'MALWARE DETECTED'
                                color = 'rgb(255, 0, 0)'
                            else:
                                continue
                            
                            # Reconstruct HTML entry
                            entry_html = f'<p style="margin: 5px 0;">'
                            entry_html += f'<span style="color: {color}; font-weight: bold;">{result}</span> | '
                            entry_html += f'<span style="color: rgb(176, 185, 197);">{parts[1].strip()}</span> | '
                            entry_html += f'<span style="color: rgb(150, 150, 150);">{parts[2].strip()}</span></p>'
                            self.memory_scan_history_text.append(entry_html)
        except Exception as e:
            print(f"Error loading history: {e}")
    
    def clear_history_file(self):
        """Clear the history file"""
        try:
            if os.path.exists(self.history_file_path):
                open(self.history_file_path, 'w').close()
        except Exception as e:
            print(f"Error clearing history file: {e}")

    def on_auto_resume_changed(self, state):
        """Handle auto-resume checkbox state change"""
        self.auto_resume_enabled = (state == Qt.Checked)
    
    def handle_force_cancel_button(self):
        """Handle Force Memory Scan / Cancel button click"""
        if self.force_memory_scan_button.text() == "Force Memory Scan":
            self.force_memory_scan()
        else:
            self.cancel_memory_scan()
    
    def cancel_memory_scan(self):
        """Cancel ongoing memory scan and resume network scanning"""
        # Stop memory progress timer
        self.memory_progress_timer.stop()
        self.memory_progress_value = 0
        self.memory_progress_bar.setValue(0)
        
        # Reset threat detection flag
        self.threat_detected = False
        
        # Hide/reset memory result label
        self.memory_result_label.setText("Waiting for network threats...")
        self.memory_result_label.setStyleSheet("color: rgb(176, 185, 197);\n"
                                                "background-color: none;\n"
                                                "border: none;\n"
                                                "font-weight: bold;")
        
        # Hide trigger source label
        self.memory_trigger_source_label.hide()
        
        # Resume network scanning
        self.is_paused = False
        self.network_scan_timer.start(0)
        
        # Reset pause button
        self.pause_scan_button.setText("Pause Scan")
        self.pause_scan_button.setEnabled(True)
        self.pause_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color: #FF9020;\n"
                                              "border: 1px solid #728EB8;\n"
                                              "border-radius: 8px;")
        
        # Reset force button
        self.force_memory_scan_button.setText("Force Memory Scan")
        self.force_memory_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                     "background-color: rgb(255, 69, 0);\n"
                                                     "border: 1px solid #728EB8;\n"
                                                     "border-radius: 8px;")
    
    def force_memory_scan(self):
        """Force memory scan to start immediately, pausing network scan"""
        if not self.threat_detected:
            # Pause network scanning
            if not self.is_paused:
                self.is_paused = True
                self.network_scan_timer.stop()
            
            # Mark threat as detected to enable memory scanning
            self.threat_detected = True
            
            # Set dummy trigger info for forced scan
            self.trigger_ip = "Manual"
            self.trigger_port = 0
            
            # Start memory scan
            self.memory_progress_value = 0
            self.memory_progress_bar.setValue(0)
            self.memory_result_label.setText("Scanning Memory")
            self.memory_result_label.setStyleSheet("color: rgb(176, 185, 197);\n"
                                                    "background-color: none;\n"
                                                    "border: none;\n"
                                                    "font-weight: bold;")
            self.memory_result_label.show()
            
            # Show trigger source
            self.memory_trigger_source_label.setText("Manually-triggered by the User")
            self.memory_trigger_source_label.show()
            
            # Disable pause button and change to resume
            self.pause_scan_button.setText("Resume Scan")
            self.pause_scan_button.setEnabled(False)
            self.pause_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                  "background-color: rgb(80, 80, 80);\n"
                                                  "border: 1px solid rgb(80, 80, 80);\n"
                                                  "border-radius: 8px;")
            
            # Start progress timer
            self.memory_progress_timer.start(100)
            
            # Change button to Cancel
            self.force_memory_scan_button.setText("Cancel")
            self.force_memory_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                         "background-color: rgb(200, 50, 50);\n"
                                                         "border: 1px solid #728EB8;\n"
                                                         "border-radius: 8px;")
    
    def run_network_scan(self):
        """Run a single network scan iteration in a separate thread"""
        # Only start a new scan if previous one is finished
        if self.scan_worker is None or not self.scan_worker.isRunning():
            self.scan_count += 1
            self.scan_worker = NetworkScanWorker()
            self.scan_worker.scan_complete.connect(self.on_scan_complete)
            self.scan_worker.start()
    
    def on_scan_complete(self, result, row_number, src_ip, src_port):
        """Handle scan completion and update UI"""
        if result[0] == 0:  # Benign
            scan_result_html = f'<table width="100%" style="margin: 3px 0; font-size: 11pt;"><tr>'
            scan_result_html += f'<td style="color: rgb(176, 185, 197); text-align: left;">Scanning {src_ip}:{src_port}</td>'
            scan_result_html += f'<td style="color: rgb(0, 255, 0); text-align: right;">Benign</td></tr></table>'
        else:  # Malicious/Suspicious
            scan_result_html = f'<table width="100%" style="margin: 3px 0; font-size: 11pt;"><tr>'
            scan_result_html += f'<td style="color: rgb(255, 144, 32); text-align: left;">Scanning {src_ip}:{src_port}</td>'
            scan_result_html += f'<td style="color: rgb(255, 144, 32); text-align: right;">Malicious</td></tr></table>'
        
        # Append to the text display
        self.network_scan_results_text.append(scan_result_html)
        
        # Auto-scroll to bottom
        scrollbar = self.network_scan_results_text.verticalScrollBar()
        scrollbar.setValue(scrollbar.maximum())
        
        # If malicious, also add to the malicious frame
        if result[0] == 1:
            malicious_html = f'<p style="margin: 5px 0; font-size: 11pt;">'
            malicious_html += f'<span style="color: rgb(255, 144, 32);">THREAT DETECTED: </span>'
            malicious_html += f'<span style="color: rgb(255, 255, 255);">{src_ip}:{src_port}</span></p>'
            
            self.malicious_scan_results_text.append(malicious_html)
            
            # Auto-scroll to bottom
            mal_scrollbar = self.malicious_scan_results_text.verticalScrollBar()
            mal_scrollbar.setValue(mal_scrollbar.maximum())
            
            # Pause network scanning and start memory progress bar
            if not self.threat_detected:
                self.threat_detected = True
                self.trigger_ip = src_ip
                self.trigger_port = src_port
                self.network_scan_timer.stop()
                self.is_paused = True
                self.pause_scan_button.setText("Resume Scan")
                self.pause_scan_button.setStyleSheet("color: rgb(150, 150, 150);\n"
                                                      "background-color: rgb(80, 80, 80);\n"
                                                      "border: 1px solid rgb(80, 80, 80);\n"
                                                      "border-radius: 8px;")
                self.pause_scan_button.setEnabled(False)
                # Start memory progress bar animation
                self.memory_progress_value = 0
                self.memory_progress_bar.setValue(0)
                # Update label to show scanning in progress
                self.memory_result_label.setText("Scanning Memory")
                self.memory_result_label.setStyleSheet("color: rgb(82, 161, 252);\n"
                                                        "background-color: none;\n"
                                                        "border: none;\n"
                                                        "font-weight: bold;")
                
                # Show trigger source
                self.memory_trigger_source_label.setText("Auto-triggered by Phase 1")
                self.memory_trigger_source_label.show()
                
                self.memory_progress_timer.start(100)  # Update every 100ms
                
                # Change force button to Cancel
                self.force_memory_scan_button.setText("Cancel")
                self.force_memory_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                             "background-color: rgb(200, 50, 50);\n"
                                                             "border: 1px solid #728EB8;\n"
                                                             "border-radius: 8px;")
    
    def update_memory_progress(self):
        """Update memory progress bar gradually to 100% over 10 seconds"""
        self.memory_progress_value += 1
        self.memory_progress_bar.setValue(self.memory_progress_value)
        
        if self.memory_progress_value >= 100:
            self.memory_progress_timer.stop()
            self.run_memory_scan()
            # Re-enable pause button
            self.pause_scan_button.setEnabled(True)
            self.pause_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                  "background-color: #47A025;\n"
                                                  "border: 1px solid #728EB8;\n"
                                                  "border-radius: 8px;")
            
            # Reset force button to Force Memory Scan
            self.force_memory_scan_button.setText("Force Memory Scan")
            self.force_memory_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                         "background-color: rgb(255, 69, 0);\n"
                                                         "border: 1px solid #728EB8;\n"
                                                         "border-radius: 8px;")
            
            # Hide trigger source label
            self.memory_trigger_source_label.hide()
    
    def run_memory_scan(self):
        """Run memory scan and display result"""
        # Randomly select a row from the memory dump data
        random_index = random.randint(0, len(memory_dump_df) - 1)
        print(f"DEBUG: Selected memory dump row: {random_index + 1} (0-indexed: {random_index})")
        sample_row = memory_dump_df.iloc[random_index:random_index+1]
        sample = sample_row.values
        
        # Run prediction
        memsvmPredict = mem_svm_model.predict(sample)
        
        # Display result
        self.memory_result_label.show()
        
        # Add to history with timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Format source - show port only if not manual trigger
        if self.trigger_ip == "Manual":
            source_text = "Manual"
        else:
            source_text = f"{self.trigger_ip}:{self.trigger_port}"
        
        if memsvmPredict[0] == 0:
            self.memory_result_label.setText("No Malware Detected")
            self.memory_result_label.setStyleSheet("color: rgb(0, 255, 0);"
                                                    "background-color: none;"
                                                    "border: none;"
                                                    "font-weight: bold;")
            history_entry = f'<p style="margin: 5px 0;">'
            history_entry += f'<span style="color: rgb(0, 255, 0); font-weight: bold;">NO MALWARE DETECTED</span> | '
            history_entry += f'<span style="color: rgb(176, 185, 197);">Source: {source_text}</span> | '
            history_entry += f'<span style="color: rgb(150, 150, 150);">{timestamp}</span></p>'
        else:
            self.memory_result_label.setText("Malware Detected")
            self.memory_result_label.setStyleSheet("color: rgb(255, 0, 0);"
                                                    "background-color: none;"
                                                    "border: none;"
                                                    "font-weight: bold;")
            history_entry = f'<p style="margin: 5px 0;">'
            history_entry += f'<span style="color: rgb(255, 0, 0); font-weight: bold;">MALWARE DETECTED</span> | '
            history_entry += f'<span style="color: rgb(176, 185, 197);">Source: {source_text}</span> | '
            history_entry += f'<span style="color: rgb(150, 150, 150);">{timestamp}</span></p>'
        
        # Append to history
        self.memory_scan_history_text.append(history_entry)
        
        # Save to file
        self.save_history_entry(history_entry)
        
        # Auto-scroll to bottom
        history_scrollbar = self.memory_scan_history_text.verticalScrollBar()
        history_scrollbar.setValue(history_scrollbar.maximum())
        
        # Auto-resume if enabled
        if self.auto_resume_enabled:
            QTimer.singleShot(1000, self.auto_resume_scan)
    
    def auto_resume_scan(self):
        """Auto-resume network scanning after memory scan completes"""
        if self.is_paused and self.auto_resume_enabled:
            self.toggle_pause_scan()
    
    def toggle_pause_scan(self):
        """Toggle pause/resume scanning"""
        if self.is_paused:
            # Resume scanning - reset memory scan
            self.is_paused = False
            self.threat_detected = False
            self.memory_progress_timer.stop()
            self.memory_progress_value = 0
            self.memory_progress_bar.setValue(0)
            self.memory_result_label.setText("Waiting for network threats...")
            self.memory_result_label.setStyleSheet("color: rgb(176, 185, 197);\n"
                                                    "background-color: none;\n"
                                                    "border: none;\n"
                                                    "font-weight: bold;")
            self.network_scan_timer.start(0)
            self.pause_scan_button.setText("Pause Scan")
            self.pause_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                  "background-color: #FF9020;\n"
                                                  "border: 1px solid #728EB8;\n"
                                                  "border-radius: 8px;")
            
            # Reset force button
            self.force_memory_scan_button.setText("Force Memory Scan")
            self.force_memory_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                         "background-color: rgb(255, 69, 0);\n"
                                                         "border: 1px solid #728EB8;\n"
                                                         "border-radius: 8px;")
        else:
            # Pause scanning
            self.is_paused = True
            self.network_scan_timer.stop()
            self.pause_scan_button.setText("Resume Scan")
            self.pause_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                  "background-color: #47A025;\n"
                                                  "border: 1px solid #728EB8;\n"
                                                  "border-radius: 8px;")
    
    def animate_scan_start(self):
        # Start continuous network scanning
        self.scan_count = 0
        NetworkScanWorker.current_row_index = 0
        self.is_paused = False
        self.threat_detected = False
        self.memory_progress_value = 0
        self.memory_progress_bar.setValue(0)
        self.memory_result_label.hide()
        self.network_scan_results_text.clear()
        self.malicious_scan_results_text.clear()
        self.run_network_scan()
        self.network_scan_timer.start(0)
        
        # Reset pause button
        self.pause_scan_button.setText("Pause Scan")
        self.pause_scan_button.setStyleSheet("color: rgb(255, 255, 255);\n"
                                              "background-color: #FF9020;\n"
                                              "border: 1px solid #728EB8;\n"
                                              "border-radius: 8px;")
        
        # text labels
        self.two_phase_text_label.hide()
        self.malware_detection_text_label.hide()
        self.description_text_label.hide()
        self.scan_icon.hide()
        self.ready_to_scan_text_label.hide()
        self.start_scan_desription.hide()
        self.start_scan_button.hide()
        
        # new scan button
        self.new_scan_button.show()
        self.pause_scan_button.show()
        self.auto_resume_checkbox.show()
        self.new_scan_button_animation = QPropertyAnimation(self.new_scan_button, b"geometry")
        self.new_scan_button_animation.setDuration(800)
        self.new_scan_button_animation.setStartValue(self.new_scan_button.geometry())
        target_rect = self.new_scan_button.geometry()
        target_rect.moveTop(125)
        self.new_scan_button_animation.setEndValue(target_rect)
        self.new_scan_button_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        # phase1_frame
        self.phase1_animation = QPropertyAnimation(self.phase1_frame, b"geometry")
        self.phase1_animation.setDuration(800)
        self.phase1_animation.setStartValue(self.phase1_frame.geometry())
        target_rect1 = self.phase1_frame.geometry()
        target_rect1.moveTop(180)
        self.phase1_animation.setEndValue(target_rect1)
        self.phase1_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        # phase2_frame
        self.phase2_animation = QPropertyAnimation(self.phase2_frame, b"geometry")
        self.phase2_animation.setDuration(800)
        self.phase2_animation.setStartValue(self.phase2_frame.geometry())
        target_rect2 = self.phase2_frame.geometry()
        target_rect2.moveTop(180)
        self.phase2_animation.setEndValue(target_rect2)
        self.phase2_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        # start_scan_frame
        self.start_scan_animation = QPropertyAnimation(self.start_scan_frame, b"geometry")
        self.start_scan_animation.setDuration(800)
        self.start_scan_animation.setStartValue(self.start_scan_frame.geometry())
        target_rect3 = self.start_scan_frame.geometry()
        target_rect3.setHeight(550)
        target_rect3.moveTop(300)
        self.start_scan_animation.setEndValue(target_rect3)
        self.start_scan_animation.setEasingCurve(QEasingCurve.InOutCubic)
        self.start_scan_frame.setStyleSheet("background-color: rgb(13, 22, 51);\n"
        "border-radius: 15px;\n"
        "border: 1px solid #728EB8;")
        
        # notes_label animation
        self.notes_label.show()
        self.notes_animation = QPropertyAnimation(self.notes_label, b"geometry")
        self.notes_animation.setDuration(800)
        self.notes_animation.setStartValue(self.notes_label.geometry())
        target_rect4 = self.notes_label.geometry()
        target_rect4.moveTop(275)
        self.notes_animation.setEndValue(target_rect4)
        self.notes_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        self.new_scan_button_animation.start()
        self.network_scanning_list_frame.show()
        self.network_scanning_list_frame_2.show()
        self.network_active_scanning_text_label.show()
        self.start_scan_memory_frame.show()
        
        self.memory_active_scanning_text_label.show()
        self.memory_active_scanning_icon.show()
        self.force_memory_scan_button.show()
        
        # Show waiting message for memory scan
        self.memory_result_label.show()
        self.memory_result_label.setText("Waiting for network threats...")
        self.memory_result_label.setStyleSheet("color: rgb(176, 185, 197);\n"
                                                "background-color: none;\n"
                                                "border: none;\n"
                                                "font-weight: bold;")
        
        # Update scroll content height
        def update_scroll_height():
            new_height = 300 + 550 + 50 + 550 + 50
            self.scroll_content.setMinimumSize(1440, new_height)
        
        self.start_scan_animation.finished.connect(update_scroll_height)
        
        # Start animations
        self.phase1_animation.start()
        self.phase2_animation.start()
        self.network_active_scanning_icon.show()
        self.start_scan_animation.start()
        self.notes_animation.start()
    
    def reset_to_initial_state(self):
        # Stop continuous scanning
        self.network_scan_timer.stop()
        self.memory_progress_timer.stop()
        if self.scan_worker and self.scan_worker.isRunning():
            self.scan_worker.quit()
            self.scan_worker.wait()
        self.scan_count = 0
        NetworkScanWorker.current_row_index = 0
        self.is_paused = False
        self.threat_detected = False
        self.memory_progress_value = 0
        
        # Clear scan results
        self.network_scan_results_text.clear()
        self.malicious_scan_results_text.clear()
        
        # Hide scanning elements
        self.new_scan_button.hide()
        self.pause_scan_button.hide()
        self.auto_resume_checkbox.hide()
        self.notes_label.hide()
        self.network_scanning_list_frame.hide()
        self.network_scanning_list_frame_2.hide()
        self.network_active_scanning_text_label.hide()
        self.network_active_scanning_icon.hide()
        self.start_scan_memory_frame.hide()
        self.memory_active_scanning_text_label.hide()
        self.memory_active_scanning_icon.hide()
        self.memory_result_label.hide()
        self.force_memory_scan_button.hide()
        self.memory_trigger_source_label.hide()
        
        # Animate new scan button back to original position
        self.new_scan_button_reset_animation = QPropertyAnimation(self.new_scan_button, b"geometry")
        self.new_scan_button_reset_animation.setDuration(800)
        self.new_scan_button_reset_animation.setStartValue(self.new_scan_button.geometry())
        self.new_scan_button_reset_animation.setEndValue(QtCore.QRect(1109, 370, 167, 42))
        self.new_scan_button_reset_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        # Animate phase1_frame back to original position
        self.phase1_reset_animation = QPropertyAnimation(self.phase1_frame, b"geometry")
        self.phase1_reset_animation.setDuration(800)
        self.phase1_reset_animation.setStartValue(self.phase1_frame.geometry())
        self.phase1_reset_animation.setEndValue(QtCore.QRect(164, 424, 531, 80))
        self.phase1_reset_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        # Animate phase2_frame back to original position
        self.phase2_reset_animation = QPropertyAnimation(self.phase2_frame, b"geometry")
        self.phase2_reset_animation.setDuration(800)
        self.phase2_reset_animation.setStartValue(self.phase2_frame.geometry())
        self.phase2_reset_animation.setEndValue(QtCore.QRect(745, 424, 531, 80))
        self.phase2_reset_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        # Animate start_scan_frame back to original position and size
        self.start_scan_reset_animation = QPropertyAnimation(self.start_scan_frame, b"geometry")
        self.start_scan_reset_animation.setDuration(800)
        self.start_scan_reset_animation.setStartValue(self.start_scan_frame.geometry())
        self.start_scan_reset_animation.setEndValue(QtCore.QRect(164, 544, 1112, 419))
        self.start_scan_reset_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        # Animate notes_label back to original position
        self.notes_reset_animation = QPropertyAnimation(self.notes_label, b"geometry")
        self.notes_reset_animation.setDuration(800)
        self.notes_reset_animation.setStartValue(self.notes_label.geometry())
        self.notes_reset_animation.setEndValue(QtCore.QRect(164, 514, 600, 25))
        self.notes_reset_animation.setEasingCurve(QEasingCurve.InOutCubic)
        
        # Reset start scan frame style
        self.start_scan_frame.setStyleSheet("background-color: rgba(13, 22, 51, 0.4);\n"
        "border-radius: 15px;")
        
        # Function to show initial elements and hide new scan button after animation
        def on_reset_complete():
            self.two_phase_text_label.show()
            self.malware_detection_text_label.show()
            self.description_text_label.show()
            self.scan_icon.show()
            self.ready_to_scan_text_label.show()
            self.start_scan_desription.show()
            self.start_scan_button.show()
            self.scroll_content.setMinimumSize(1440, 980)
        
        self.start_scan_reset_animation.finished.connect(on_reset_complete)
        
        # Start all animations
        self.new_scan_button_reset_animation.start()
        self.phase1_reset_animation.start()
        self.phase2_reset_animation.start()
        self.start_scan_reset_animation.start()
        self.notes_reset_animation.start()
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_scan_button.setText(_translate("MainWindow", "New Scan"))
        self.pause_scan_button.setText(_translate("MainWindow", "Pause Scan"))
        self.two_phase_text_label.setText(_translate("MainWindow", "Two-Phase Fileless"))
        self.malware_detection_text_label.setText(_translate("MainWindow", "Malware Detection"))
        self.description_text_label.setText(_translate("MainWindow", "FYLEX uses a dual-phase scanning to identify and validate fileless malware behaviors.  Network scanning detects anomalies, then memory scanning confirms the presence of malicious code."))
        self.phase1_text_label.setText(_translate("MainWindow", "Phase 1"))
        self.network_scanning_text_label.setText(_translate("MainWindow", "Network Scanning"))
        self.ready_to_scan_text_label.setText(_translate("MainWindow", "Ready to Scan"))
        self.start_scan_desription.setText(_translate("MainWindow", "Click”Start Detection”to begin the two-phase filess malware detection process"))
        self.start_scan_button.setText(_translate("MainWindow", "Start Detection"))
        self.phase2_text_label.setText(_translate("MainWindow", "Phase 2"))
        self.memory_scanning_text_label.setText(_translate("MainWindow", "Memory Scanning"))
        self.network_active_scanning_text_label.setText(_translate("MainWindow", "Phase 1: Network Scanning"))
        self.memory_active_scanning_text_label.setText(_translate("MainWindow", "Phase 2: Memory Scanning"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())